name: QA Workflow Services

on:
  # [QA Workflow Toolbox]-[AC.3]: Manual Trigger Support
  workflow_dispatch:
  # Any feature branch PR to QA or direct push to QA will trigger this workflow
  pull_request:
    types:
      - opened       # Only when PR is first opened
    branches:
      - qa           # Target branch (base) must be QA
      - 'qa/**'
  # [QA Workflow Toolbox]-[AC.1]: Automatic Trigger on QA Branch
  push:
    branches:
      - 'qa'
      - 'qa/**'

run-name: "[QA]: ${{ github.event_name }} at ${{ github.ref_name }} (${{ github.sha }})"

jobs:
  set-configuration:
    name: Setup configuration based on the trigger event
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.determine.outputs.environment }}
      has_open_pr_to_qa: ${{ steps.check_pr.outputs.has_open_pr_to_qa }}
    steps:
      - id: determine
        name: Set environment to QA
        run: |
          echo "environment=QA" >> $GITHUB_OUTPUT
          echo "The matching deployment's environment is QA"

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
      
      - uses: actions/checkout@v4

      # [QA Workflow Toolbox]-[AC.4]: Branch Parameterization for Manual Runs
      - name: Check if branch has open PR to QA
        id: check_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          branch="${{ github.ref_name }}"
          pr_count=$(gh pr list --base qa --head "$branch" --state open --json number --jq 'length')
          if [ "$pr_count" -gt 0 ]; then
            echo "has_open_pr_to_qa=true" >> $GITHUB_OUTPUT
          else
            echo "has_open_pr_to_qa=false" >> $GITHUB_OUTPUT
          fi

  # [QA Workflow Toolbox]-[AC.3][AC.4]: Manual trigger fails if branch does not have PR to QA
  manual-trigger-branch-doest-not-have-pr-to-qa:
    name: Manual trigger on branch that does not have PR to QA
    runs-on: ubuntu-latest
    needs: set-configuration
    if: ${{ github.event_name== 'workflow_dispatch' && needs.set-configuration.outputs.has_open_pr_to_qa == 'false' }} 
    steps:
      - name: Fail the workflow
        run: |
          echo "The branch '${{ github.event.inputs.pull_request_branch }}' does not have an open PR to QA."
          echo "Please create a PR to QA before triggering this workflow manually."
          exit 1

  # [QA Workflow Toolbox]-[AC.5][AC.6]: Consistent QA Checks & Execution Feedback
  # [QA Workflow Toolbox]-[AC.2][AC.3]: Run for PRs to QA or manual trigger with PR to QA
  call-pr-ci-workflow:
    name: Pull Request CI Workflow
    needs: set-configuration
    # Only run this job if it's a PR event or if the specified branch has an open PR to QA when triggered manually
    if: ${{ github.event_name== 'pull_request' || (github.event_name== 'workflow_dispatch' && needs.set-configuration.outputs.has_open_pr_to_qa == 'true') }} 
    uses: DUMMY_CI_WORKFLOW_PATH
    with:
      # Mandatory inputs
      environment: ${{ needs.set-configuration.outputs.environment }}
      service-name: pfh-user-service

      # Custom
      custom-test-script: DUMMY_CUSTOM_TEST_SCRIPTS
      custom-build-script: DUMMY_CUSTOM_BUILD_SCRIPTS
    
    secrets:
      deploy_token: ${{ secrets.DEPLOY_TOKEN }}