name: Security & Compliance Stage

on:
  workflow_call:
    inputs:
      runner:
        description: "Choose runner"
        type: string
        required: true
        default: "ubuntu-latest"

jobs:
    security-and-compliance-check:
        name: Security and Compliance Check
        runs-on: ${{ inputs.runner }}

        steps:
            - name: Docker Image Scanning
              run:  echo "Docker Image Scanning"
                
            - name: Policy enforcement
              run: echo "Run OPA or Sentinel policies"

            - name: Audit logging
              run: echo "Log evidence for compliance"

            - name: Sign Docker images
              run: echo "Sign Docker images with cryptographic signatures before push them to Registry"


