name: Build & Test Stage

# ## **User Story: Automated Build & Test Execution**

# * **As a** developer
# * **I want** automated build and test execution triggered on every code commit
# * **So that** I get fast feedback on code quality and can fix issues immediately

# ✅ **Acceptance Criteria:**

# - [ ] **AC.1:** Build triggers automatically within 30 seconds of code push
# - [ ] **AC.2:** Containerized build environment ensures consistent results across all environments
# - [ ] **AC.3:** Build completes within 5 minutes to maintain fast feedback loops
# - [ ] **AC.4:** Failed builds immediately notify the developer via preferred channel (Slack/email)
# - [ ] **AC.5:** Build logs are easily accessible and searchable for troubleshooting
# - [ ] **AC.6:** Build artifacts are automatically versioned with semantic versioning + Git SHA

# ---

# ## **User Story: Parallel Test Suite Execution**

# * **As a** developer
# * **I want** test suites to run in parallel with fail-fast behavior
# * **So that** I minimize cycle time and get rapid feedback on test failures

# ✅ **Acceptance Criteria:**

# - [ ] **AC.1:** Unit tests, integration tests, and contract tests execute in parallel
# - [ ] **AC.2:** Test execution stops immediately on first critical failure (fail-fast)
# - [ ] **AC.3:** Test results available within 8 minutes of build start
# - [ ] **AC.4:** Flaky test detection automatically retries unstable tests up to 3 times
# - [ ] **AC.5:** Test execution time trends tracked to identify performance degradation
# - [ ] **AC.6:** Test reports include detailed failure analysis and stack traces

# ---


on:
  # [Automated Build & Test Execution]-[AC.1]: 
  #   If the caller call this workflow, then it will automatically triggered 
  #   according to the event trigger of the caller. In this case the caller 
  #   should be config to be trigger CI build with event push
  workflow_call:
    inputs:
      runner:
        description: "Choose runner"
        type: string
        required: true
        default: "ubuntu-latest"
      registry:
        description: "Enable container registry access (true/false)"
        type: string
        required: false
        default: "false"
      report:
        description: "Enable regression report upload (true/false)"
        type: boolean
        required: false
        default: true

jobs:
  build:
    name: Build & Test
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: echo "Install dependencies and setup build tools"

      - name: Build application
        run: echo "Run your build command here"

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Run tests
        run: echo "Run unit, integration, and regression tests"

      - name: Code coverage
        run: echo "Generate and upload coverage report"


