name: DEV Commit Fast Feedback
on:
  workflow_dispatch:
    inputs:
        # ============ INPUT CONFIGURATION ============
        service-name:
            description: Name of the service
            required: true
            type: string
    
        # ============ CUSTOM SCRIPT ============
        custom-test-script:
            description: Custom script to test
            type: string
            required: false
            
        custom-build-script:
            description: Custom script to build
            type: string
            required: false

  workflow_call:
    inputs:
      # ============ INPUT CONFIGURATION ============
      environment:
        required: true
        type: string
      service-name:
        required: true
        type: string

      # ============ CUSTOM SCRIPT ============
      custom-test-script:
        description: Custom script to test
        type: string
        required: false
      custom-build-script:
        description: Custom script to build
        type: string
        required: false    

    secrets:
      deploy_token:
        required: true


jobs:
  # 🛠️ Stage 1: Source Control & Validation
  source-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Static code analysis
        run: |
          echo "Run SonarQube for Quality Gates"
          echo "Run SonarQube for SAST"

  # 🔍 Stage 2: Build & Compile & Testing
  build-test:
    uses: ./.github/workflows/build-test-stage-template.yml
    with:
      runner:               ubuntu-latest
      registry:             false
      report:               false
      custom-test-script:   ${{ inputs.custom-test-script }}
      custom-build-script:  ${{ inputs.custom-build-script }}  