name: QA Pull Request CI
on:
  # For testing purpose
  workflow_dispatch:
    inputs:
      environment:
        description: Choose an environment for testing
        required: true
        type: choice
        options:
          - Feature
          - Development
          - QA
          - UAT
          - Production

  workflow_call:
    inputs:
      # ============ INPUT CONFIGURATION ============
      environment:
        required: true
        type: string
      service-name:
        required: true
        type: string

      # ============ CUSTOM SCRIPT ============
      custom-test-script:
        description: Custom script to test
        type: string
        required: false
      custom-build-script:
        description: Custom script to build
        type: string
        required: false    

    secrets:
      deploy_token:
        required: true

jobs:
  # 🛠️ Stage 1: Source Control & Validation
  # [Mandatory Checklist at PR into QA]-[AC.1]: Automatic linting, static analysis.
  source-validation:
    runs-on: ubuntu-latest
    name: "[BOILERPLATE] Lint and Static Analysis"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Static code analysis
        run: |
          echo "Run SonarQube for Quality Gates"
          echo "Run SonarQube for SAST"

  # 🔍 Stage 2: Build & Compile & Testing
  # [Mandatory Checklist at PR into QA]-[AC.2]: Full test suite for component and functionality.
  # [Mandatory Checklist at PR into QA]-[AC.3]: Build and packaging the build artifact into Docker image for delivery
  # [Mandatory Checklist at PR into QA]-[AC.5]: Build artifact shall be tagged with the current git commit
  build-test:
    uses: ./.github/workflows/_build-test-stage.yml
    with:
      runner:               ubuntu-latest
      registry:             false
      report:               false
      custom-test-script:   ${{ inputs.custom-test-script }}
      custom-build-script:  ${{ inputs.custom-build-script }}

  # [Mandatory Checklist at PR into QA]-[AC.7.1]: Automatically add PIC for QA branch to PR's review if not already (boilerplate)
  mandatory-pr-reviewers:
    runs-on: ubuntu-latest
    needs: build-test
    name: "[BOILERPLATE] Mandatory PR reviewers check"
    steps:
      - name: Add Mandatory PR reviewers
        run: echo "Run Mandatory PR reviewers"

  # 🔐 Stage 3: Security & Compliance Gate
  # [Mandatory Checklist at PR into QA]-[AC.4.1]: Dependency vulnerability checks and license compliance (boilerplate)
  compliance-check:
    needs:
      - mandatory-pr-reviewers
    uses: ./.github/workflows/_security-compliance-stage.yml
    with:
      runner: ubuntu-latest

  # 📦 Stage 4: Artifact Management
  # [Mandatory Checklist at PR into QA]-[AC.5.1]: Actual artifact handling stage (boilerplate)
  artifact-handling:
    runs-on: ubuntu-latest
    needs: mandatory-pr-reviewers
    name: "[BOILERPLATE] Artifact handling"
    steps:
      - name: Push Docker Image to Registry
        run: echo "Push Docker Image to Registry"

      - name: Save Test report to Artifact
        run: echo "Save Test report to Artifact" 

      - name: Save Security Audit log to Artifact
        run: echo "Save Security Audit log to Artifact"

  # 📦 Stage 5: Deployment
  # [Mandatory Checklist at PR into QA]-[AC.6.1]: Deployment should be run only when trigger manually (boilerplate)
  deploy:
    runs-on: ubuntu-latest
    needs: artifact-handling
    name: "[BOILERPLATE] Approve for Deployment"
    steps:
      - name: Manual trigger the "Deployment Workflows Service" to proceed with the deployment
        run: echo "More detail, please check with the PIC for the deployment"